migration of internal summary
neo4jrb/neo4j-ruby-driver pull request #102
Opened 2021-12-23 17:54 UTC by mrhardikjoshi

2021-12-24 13:08 UTC, klobuczek requested changes

2021-12-24 13:10 UTC, klobuczek commented on ruby/neo4j/driver/internal/summary/internal_server_info.rb
> +    end
I actually meant the `eql?` method above.

2021-12-24 15:23 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/summary/internal_summary_counters.rb
> +      "}"
Ohk, `Struct` already has `to_s` implemented in it so I am going to remove these `to_s` from all of these classes.

2021-12-24 15:27 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/summary/internal_server_info.rb
> +    end
Hmm yes, I have removed the `eql?` so that it uses `Struct`'s method which compares all attributes.

2021-12-24 15:42 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/summary/internal_input_position.rb
> +      "offset=#{offset}, line=#{line}, column=#{column}"
the default `Struct` gives following string so I have removed to_s methods from these classes.
```
irb(main):009:0> InternalInputPosition.new(3, 4, 8).to_s
=> "#<struct InternalInputPosition offset=3, line=4, column=8>"
```

2021-12-25 17:10 UTC, klobuczek approved these changes

2021-12-25 17:10 UTC, merged