driver_metrics config added
neo4jrb/neo4j-ruby-driver pull request #150
Opened 2022-05-09 18:07 UTC by Kinju011

2022-05-09 20:13 UTC, klobuczek commented
@Kinju011 in Neo4j::Driver::Ext::ConfigConverter handle `driver_metrics` in similar way `encryption` is handled. Avoid any duplication.

2022-05-10 05:35 UTC, Kinju011 commented
> @Kinju011 in Neo4j::Driver::Ext::ConfigConverter handle `driver_metrics` in similar way `encryption` is handled. Avoid any duplication.

okay, thanks
will do that.

2022-05-10 13:51 UTC, klobuczek requested changes

2022-05-10 13:51 UTC, klobuczek commented on jruby/neo4j/driver/ext/config_converter.rb
> +            value = nil
as I mentioned earlier this should be solved in a more DRY way

2022-05-10 14:35 UTC, Kinju011 commented on jruby/neo4j/driver/ext/config_converter.rb
> +            value = nil
okay, updating it it.

2022-05-10 16:10 UTC, klobuczek approved these changes

2022-05-10 16:10 UTC, merged