fixed the example spec with neo4j scheme
neo4jrb/neo4j-ruby-driver pull request #198
Opened 2022-09-14 14:11 UTC by Kinju011

2022-09-16 07:50 UTC, klobuczek requested changes

2022-09-16 07:50 UTC, klobuczek commented on lib/neo4j/driver/exceptions/socket_exception.rb
> +end
let's don't introduce new Neo4j exception but just catch SocketError below

2022-09-16 07:50 UTC, klobuczek commented on ruby/neo4j/driver/internal/cluster/rediscovery_impl.rb
>              exception&.add_suppressed(e)
```suggestion
          rescue SocketError => e
```
let's just store the 1st exception. There is not much info in those exceptions anyway.

2022-09-16 07:50 UTC, klobuczek commented on spec/neo4j/driver/dev_manual_examples_spec.rb
>      context 'Example 2.3. Custom Address Resolver' do
let's add something like
```
      let(:uri) { 'neo4j://nonexisting' }
```
so the spec is effective regardless of the global scheme.

2022-09-16 08:20 UTC, Kinju011 commented on lib/neo4j/driver/exceptions/socket_exception.rb
> +end
okay

2022-09-16 22:42 UTC, klobuczek commented
@Kinju011 the spec in this PR was not testing properly, that's why the spec was passing. The spec should be passing in the current form after my modification. Unfortunately this is not happening even for jruby.

2022-09-17 13:05 UTC, klobuczek commented
had to move the spec cluster spec as the resolver is effective only in cluster

2022-09-17 13:09 UTC, klobuczek approved these changes

2022-09-17 13:10 UTC, merged