Internal async pool conversion
neo4jrb/neo4j-ruby-driver pull request #86
Opened 2021-12-08 13:54 UTC by Kinju011

Internal=>Async=>Pool directory files converted

2021-12-08 14:34 UTC, klobuczek requested changes

2021-12-08 14:34 UTC, klobuczek commented on ruby/neo4j/driver/internal/async/pool/pool_settings.rb
> +          end
those methods are already defined by `attr_reader`

2021-12-08 17:31 UTC, klobuczek requested changes

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/connection_pool_impl.rb
> +              end
Spacing issue
```suggestion
            channel_future.handle do |channel, error|
              begin
                process_acquisition_error(pool, address, error)
                assert_not_closed(address, channel, pool)
                Connection::ChannelAttributes.set_authorization_state_listener(channel, channel_health_checker)
                connection = connection_factory.create_connection(channel, pool)

                metrics_listener.after_acquired_or_created(pool.id, acquire_event)
                connection
              ensure
                metrics_listener.after_acquiring_or_creating(pool.id)
              end
            end
```

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/connection_pool_impl.rb
> +              end
This is not aligned correctly

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/connection_pool_impl.rb
> +            Util::LockUtil.execute_with_lock(address_to_pool_lock.read_lock, -> () {"ConnectionPoolImpl{ pools=#{address_to_pool}}"}.call)
```suggestion
            Util::LockUtil.execute_with_lock(address_to_pool_lock.read_lock) { "ConnectionPoolImpl{ pools=#{address_to_pool}}" })
```

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/netty_channel_pool.rb
> +
not needed as `id` is marked with `attr_reader` above
```suggestion
```

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/netty_channel_pool.rb
> +          attr_reader :delegate, :closed, :id, :close_future
only `id` was exposed with reader, in original class unless I am missing something here.

```suggestion
          attr_reader :id
```

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/pool_settings.rb
> +          DEFAULT_MAX_CONNECTION_LIFETIME = java.util.concurrent.TimeUnit::HOURS.to_millis(1)
```suggestion
          DEFAULT_MAX_CONNECTION_LIFETIME = 60*60*1000 # in milliseconds
```

2021-12-09 16:30 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/pool_settings.rb
> +          DEFAULT_CONNECTION_ACQUISITION_TIMEOUT = java.util.concurrent.TimeUnit::SECONDS.to_millis(60)
```suggestion
          DEFAULT_CONNECTION_ACQUISITION_TIMEOUT = 60 * 1000 # in milliseconds
```

2021-12-09 17:23 UTC, mrhardikjoshi commented on ruby/neo4j/driver/internal/async/pool/connection_pool_impl.rb
> +            Util::LockUtil.execute_with_lock(address_to_pool_lock.read_lock) { "ConnectionPoolImpl{ pools=#{address_to_pool}}" })
```suggestion
            Util::LockUtil.execute_with_lock(address_to_pool_lock.read_lock) { "ConnectionPoolImpl{ pools=#{address_to_pool}}" }
```

2021-12-09 18:44 UTC, merged